import { describe, expect, test } from "bun:test";
import { config } from "@automend/shared";

/**
 * `components/ui/sidebar.tsx` is generated by the shadcn CLI, so the cookie name it writes is not ours
 * to export from there — `lib/sidebar-state.ts` reads it by name instead. This is what makes that safe:
 * regenerate the component with a different name and this fails, rather than the sidebar quietly
 * forgetting its state on every reload.
 */
describe("the sidebar state cookie", () => {
  const component = Bun.file(`${import.meta.dir}/../src/components/ui/sidebar.tsx`);

  test("is the name the vendored component writes", async () => {
    expect(await component.text()).toContain(`SIDEBAR_COOKIE_NAME = "${config.webClient.sidebar.cookieName}"`);
  });
});
