/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppRouteImport } from './routes/app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing.privacy'
import { Route as MarketingStatusRouteImport } from './routes/_marketing.status'
import { Route as MarketingTosRouteImport } from './routes/_marketing.tos'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppConnectionsRouteImport } from './routes/app/connections'
import { Route as AppOperationsRouteImport } from './routes/app/operations'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppFlowsIndexRouteImport } from './routes/app/flows/index'
import { Route as AppFlowsFlowIdRouteImport } from './routes/app/flows/$flowId'
import { Route as AppRunsIndexRouteImport } from './routes/app/runs/index'
import { Route as AppRunsRunIdRouteImport } from './routes/app/runs/$runId'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingStatusRoute = MarketingStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTosRoute = MarketingTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => MarketingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsRoute = AppOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsIndexRoute = AppFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsFlowIdRoute = AppFlowsFlowIdRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/status': typeof MarketingStatusRoute
  '/tos': typeof MarketingTosRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/operations': typeof AppOperationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/app/flows/': typeof AppFlowsIndexRoute
  '/app/runs/': typeof AppRunsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/status': typeof MarketingStatusRoute
  '/tos': typeof MarketingTosRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/operations': typeof AppOperationsRoute
  '/app/profile': typeof AppProfileRoute
  '/': typeof MarketingIndexRoute
  '/app': typeof AppIndexRoute
  '/app/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/app/flows': typeof AppFlowsIndexRoute
  '/app/runs': typeof AppRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/status': typeof MarketingStatusRoute
  '/_marketing/tos': typeof MarketingTosRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/operations': typeof AppOperationsRoute
  '/app/profile': typeof AppProfileRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/app/flows/': typeof AppFlowsIndexRoute
  '/app/runs/': typeof AppRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/privacy'
    | '/status'
    | '/tos'
    | '/app/connections'
    | '/app/operations'
    | '/app/profile'
    | '/app/'
    | '/app/flows/$flowId'
    | '/app/runs/$runId'
    | '/app/flows/'
    | '/app/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/privacy'
    | '/status'
    | '/tos'
    | '/app/connections'
    | '/app/operations'
    | '/app/profile'
    | '/'
    | '/app'
    | '/app/flows/$flowId'
    | '/app/runs/$runId'
    | '/app/flows'
    | '/app/runs'
  id:
    | '__root__'
    | '/_marketing'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/_marketing/privacy'
    | '/_marketing/status'
    | '/_marketing/tos'
    | '/app/connections'
    | '/app/operations'
    | '/app/profile'
    | '/_marketing/'
    | '/app/'
    | '/app/flows/$flowId'
    | '/app/runs/$runId'
    | '/app/flows/'
    | '/app/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/status': {
      id: '/_marketing/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof MarketingStatusRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/tos': {
      id: '/_marketing/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof MarketingTosRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections': {
      id: '/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operations': {
      id: '/app/operations'
      path: '/operations'
      fullPath: '/app/operations'
      preLoaderRoute: typeof AppOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flows/': {
      id: '/app/flows/'
      path: '/flows'
      fullPath: '/app/flows/'
      preLoaderRoute: typeof AppFlowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flows/$flowId': {
      id: '/app/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/app/flows/$flowId'
      preLoaderRoute: typeof AppFlowsFlowIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs/': {
      id: '/app/runs/'
      path: '/runs'
      fullPath: '/app/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs/$runId': {
      id: '/app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/app/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingStatusRoute: typeof MarketingStatusRoute
  MarketingTosRoute: typeof MarketingTosRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingStatusRoute: MarketingStatusRoute,
  MarketingTosRoute: MarketingTosRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AppRouteChildren {
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppOperationsRoute: typeof AppOperationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFlowsFlowIdRoute: typeof AppFlowsFlowIdRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
  AppFlowsIndexRoute: typeof AppFlowsIndexRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectionsRoute: AppConnectionsRoute,
  AppOperationsRoute: AppOperationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppFlowsFlowIdRoute: AppFlowsFlowIdRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
  AppFlowsIndexRoute: AppFlowsIndexRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
