/**
 * The flow definition: the document the builder edits and the engine executes.
 *
 * A definition is one trigger, the steps hanging off it, and the edges between them. It is stored whole in a
 * single `jsonb` column, so this schema is the only thing standing between the builder and the database — it
 * is applied on the way in (API request) and on the way out (job payload), never assumed.
 *
 * **This module validates structure, not meaning.** A step names a kit and an action and carries an opaque
 * `input`; whether that kit exists and whether the input suits it is checked by
 * `validateDefinitionAgainstRegistry` in `@automend/kits`. The split is forced rather than chosen: this file
 * is imported by the browser and its header promises `@automend/shared` depends on nothing, so it cannot
 * reach the registry — and a schema that could would drag every kit's code into the bundle.
 *
 * The graph rules below are the interesting part of what *is* here. They reject a definition that could not
 * be executed no matter what the engine does: an edge pointing at a node that was deleted, a cycle that
 * would never terminate, an edge into the trigger. They deliberately do *not* require the graph to be
 * finished — a step the author has not connected yet is a normal state to save in.
 */

import { z } from "zod";
import { config } from "./config";

const { flows: flowConfig, kits: kitConfig, validation } = config;

/** Node identity is generated by the client, so it is a UUID rather than a free-form string. */
const nodeIdSchema = z.uuid();

const nodeNameSchema = z.string().trim().min(validation.flowNodeName.minLength).max(validation.flowNodeName.maxLength);

/**
 * A kit id, or an action or trigger name: camelCase.
 *
 * Checked here as well as when a kit is declared, because a definition is read back out of a `jsonb` column
 * that nothing stops another writer from filling. It bounds the shape, not the existence — whether
 * `gmail.sendEmail` is real is the registry's question.
 */
const kitNameSchema = z.string().regex(new RegExp(kitConfig.namePattern), "Must be a camelCase kit identifier");

/** Canvas coordinates. Presentation, but part of the document: reopening a flow must look the same. */
export const flowNodePositionSchema = z.object({
  x: z.number().finite(),
  y: z.number().finite(),
});

/**
 * A step's configured values, as the builder saved them.
 *
 * Opaque at this level and validated against the action's own property map elsewhere. Every value is a
 * `{{variable}}`-bearing string or a plain scalar, so the record is the whole vocabulary — there is no
 * nesting, because a property is a field in a form rather than a document.
 */
const stepInputSchema = z.record(z.string(), z.unknown());

export const flowTriggerNodeSchema = z.object({
  id: nodeIdSchema,
  name: nodeNameSchema,
  position: flowNodePositionSchema,
  kitId: kitNameSchema,
  triggerName: kitNameSchema,
  input: stepInputSchema,
  /**
   * Which connection the trigger acts through. Optional because a trigger is configured before it is
   * finished — the engine is what refuses to fire one that needs a connection and names none.
   */
  connectionId: z.uuid().optional(),
});

export const flowStepNodeSchema = z.object({
  id: nodeIdSchema,
  name: nodeNameSchema,
  position: flowNodePositionSchema,
  kitId: kitNameSchema,
  actionName: kitNameSchema,
  input: stepInputSchema,
  connectionId: z.uuid().optional(),
  /**
   * Whether the run carries on when this step fails.
   *
   * The only error-handling switch here, because it is the only one the executor honours. A
   * `retryOnFailure` flag would read as a feature and do nothing — BullMQ retries the whole run, and
   * per-step retry does not exist.
   */
  continueOnFailure: z.boolean().default(false),
});

export const flowEdgeSchema = z.object({
  id: z.uuid(),
  source: nodeIdSchema,
  target: nodeIdSchema,
});

export type FlowTriggerNode = z.infer<typeof flowTriggerNodeSchema>;
export type FlowStepNode = z.infer<typeof flowStepNodeSchema>;
export type FlowEdge = z.infer<typeof flowEdgeSchema>;
export type FlowStepInput = z.infer<typeof stepInputSchema>;

const flowDefinitionShapeSchema = z.object({
  /** Stored with every flow, so a later shape change can migrate old rows instead of failing. */
  version: z.literal(flowConfig.definitionVersion),
  trigger: flowTriggerNodeSchema,
  steps: z.array(flowStepNodeSchema).max(flowConfig.maxSteps),
  edges: z.array(flowEdgeSchema),
});

type FlowDefinitionShape = z.infer<typeof flowDefinitionShapeSchema>;

/**
 * Walks the graph depth-first looking for a back edge, which is what a cycle is.
 *
 * `visiting` holds the nodes on the current path and `visited` those already cleared, so a diamond (two
 * branches rejoining) is not mistaken for a cycle the way a single "seen" set would.
 */
function hasCycle(nodeIds: string[], edges: FlowEdge[]): boolean {
  const outgoing = new Map<string, string[]>();

  for (const edge of edges) {
    const existing = outgoing.get(edge.source);

    if (existing) {
      existing.push(edge.target);
    } else {
      outgoing.set(edge.source, [edge.target]);
    }
  }

  const visiting = new Set<string>();
  const visited = new Set<string>();

  function descend(nodeId: string): boolean {
    if (visiting.has(nodeId)) {
      return true;
    }

    if (visited.has(nodeId)) {
      return false;
    }

    visiting.add(nodeId);

    for (const target of outgoing.get(nodeId) ?? []) {
      if (descend(target)) {
        return true;
      }
    }

    visiting.delete(nodeId);
    visited.add(nodeId);

    return false;
  }

  return nodeIds.some((nodeId) => descend(nodeId));
}

function checkGraph(definition: FlowDefinitionShape, ctx: z.RefinementCtx): void {
  const nodeIds = [definition.trigger.id, ...definition.steps.map((step) => step.id)];
  const knownNodeIds = new Set(nodeIds);

  if (knownNodeIds.size !== nodeIds.length) {
    ctx.addIssue({
      code: "custom",
      path: ["steps"],
      message: "Two nodes share the same id",
    });
  }

  const seenConnections = new Set<string>();

  definition.edges.forEach((edge, index) => {
    const addEdgeIssue = (message: string) => {
      ctx.addIssue({ code: "custom", path: ["edges", index], message });
    };

    if (!knownNodeIds.has(edge.source)) {
      addEdgeIssue("Edge starts at a node that does not exist");
    }

    if (!knownNodeIds.has(edge.target)) {
      addEdgeIssue("Edge ends at a node that does not exist");
    }

    if (edge.source === edge.target) {
      addEdgeIssue("A step cannot connect to itself");
    }

    // The trigger is what starts a flow, so nothing may run before it.
    if (edge.target === definition.trigger.id) {
      addEdgeIssue("Nothing can connect into the trigger");
    }

    const connection = `${edge.source}->${edge.target}`;

    if (seenConnections.has(connection)) {
      addEdgeIssue("The same two nodes are already connected");
    }

    seenConnections.add(connection);
  });

  if (hasCycle(nodeIds, definition.edges)) {
    ctx.addIssue({
      code: "custom",
      path: ["edges"],
      message: "The steps form a loop, so the flow would never finish",
    });
  }
}

export const flowDefinitionSchema = flowDefinitionShapeSchema.superRefine(checkGraph);

export type FlowDefinition = z.infer<typeof flowDefinitionSchema>;

/**
 * The address a webhook trigger listens on.
 *
 * Built from the flow's own id, so two flows can use the same path without colliding and nobody has to
 * invent a unique one. Shared rather than assembled in the UI, because the builder shows this URL and the
 * API routes on it — they must be the same string.
 */
export function buildWebhookPath(flowId: string, path: string): string {
  const suffix = path.length > 0 ? `/${path}` : "";

  return `${config.http.routes.hooks}/${flowId}${suffix}`;
}

/**
 * Reads a value a trigger stored, when it has to be a string.
 *
 * A trigger's `input` is opaque at this level, but two of its values are *addresses* rather than data — a
 * webhook's path and a cron expression — and the API has to route on one of them before any kit is involved.
 * This is the narrow, total way to ask: a missing or non-string value is undefined rather than a cast.
 */
export function readTriggerText(trigger: FlowTriggerNode, key: string): string | undefined {
  const value = trigger.input[key];

  return typeof value === "string" ? value : undefined;
}

/**
 * A brand-new flow: the trigger alone, with no steps.
 *
 * Shared rather than built in the API, so a flow created through the API and one drafted in the browser start
 * from the same document.
 */
export function createDefaultFlowDefinition(): FlowDefinition {
  const { defaultTrigger } = flowConfig;

  return {
    version: flowConfig.definitionVersion,
    trigger: {
      id: crypto.randomUUID(),
      name: defaultTrigger.name,
      position: { ...flowConfig.canvas.triggerPosition },
      kitId: defaultTrigger.kitId,
      triggerName: defaultTrigger.triggerName,
      input: {},
    },
    steps: [],
    edges: [],
  };
}
