/**
 * The flow definition: the document the builder edits and the engine will execute.
 *
 * A definition is one trigger, the steps hanging off it, and the edges between them. It is stored
 * whole in a single `jsonb` column, so this schema is the only thing standing between the builder
 * and the database — it is applied on the way in (API request) and on the way out (job payload),
 * never assumed.
 *
 * The graph rules below are the interesting part. They reject a definition that could not be
 * executed no matter what the engine does: an edge pointing at a node that was deleted, a cycle
 * that would never terminate, an edge into the trigger. They deliberately do *not* require the
 * graph to be finished — a step the author has not connected yet is a normal state to save in.
 */

import { z } from "zod";
import { config } from "./config";

const { flows: flowConfig, validation } = config;

export const FLOW_TRIGGER_KINDS = flowConfig.triggerKinds;
export const FLOW_STEP_KINDS = flowConfig.stepKinds;

export type FlowTriggerKind = (typeof FLOW_TRIGGER_KINDS)[number];
export type FlowStepKind = (typeof FLOW_STEP_KINDS)[number];

/** Node identity is generated by the client, so it is a UUID rather than a free-form string. */
const nodeIdSchema = z.uuid();

const nodeNameSchema = z.string().trim().min(validation.flowNodeName.minLength).max(validation.flowNodeName.maxLength);

/** Canvas coordinates. Presentation, but part of the document: reopening a flow must look the same. */
export const flowNodePositionSchema = z.object({
  x: z.number().finite(),
  y: z.number().finite(),
});

export const flowTriggerConfigSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("manual") }),
  z.object({
    kind: z.literal("webhook"),
    path: z.string().trim().min(validation.webhookPath.minLength).max(validation.webhookPath.maxLength),
  }),
  z.object({
    kind: z.literal("schedule"),
    /** Only length-checked here; the scheduler validates the expression when it is registered. */
    cron: z.string().trim().min(validation.cronExpression.minLength).max(validation.cronExpression.maxLength),
  }),
]);

export const flowStepConfigSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("http-request"),
    method: z.enum(flowConfig.httpMethods),
    url: z.url().max(validation.stepUrl.maxLength),
  }),
  z.object({
    kind: z.literal("send-email"),
    /**
     * Which connection to send through. Optional because a step is edited before it is finished —
     * a half-configured step must still be saveable, and the engine is what will refuse to run one
     * that names no connection.
     */
    connectionId: z.uuid().optional(),
    /** Comma-separated. Each entry may be a `{{variable}}`, so it is not validated as an address. */
    to: z.string().trim().max(validation.emailRecipients.maxLength),
    subject: z.string().max(validation.emailSubject.maxLength),
    body: z.string().max(validation.emailBody.maxLength),
  }),
  z.object({
    kind: z.literal("delay"),
    durationMs: z.number().int().min(flowConfig.delay.minMs).max(flowConfig.delay.maxMs),
  }),
  z.object({
    kind: z.literal("log"),
    message: z.string().max(validation.logMessage.maxLength),
  }),
]);

export const flowTriggerNodeSchema = z.object({
  id: nodeIdSchema,
  name: nodeNameSchema,
  position: flowNodePositionSchema,
  config: flowTriggerConfigSchema,
});

export const flowStepNodeSchema = z.object({
  id: nodeIdSchema,
  name: nodeNameSchema,
  position: flowNodePositionSchema,
  config: flowStepConfigSchema,
});

export const flowEdgeSchema = z.object({
  id: z.uuid(),
  source: nodeIdSchema,
  target: nodeIdSchema,
});

export type FlowTriggerConfig = z.infer<typeof flowTriggerConfigSchema>;
export type FlowStepConfig = z.infer<typeof flowStepConfigSchema>;
export type FlowTriggerNode = z.infer<typeof flowTriggerNodeSchema>;
export type FlowStepNode = z.infer<typeof flowStepNodeSchema>;
export type FlowEdge = z.infer<typeof flowEdgeSchema>;

const flowDefinitionShapeSchema = z.object({
  /** Stored with every flow, so a later shape change can migrate old rows instead of failing. */
  version: z.literal(flowConfig.definitionVersion),
  trigger: flowTriggerNodeSchema,
  steps: z.array(flowStepNodeSchema).max(flowConfig.maxSteps),
  edges: z.array(flowEdgeSchema),
});

type FlowDefinitionShape = z.infer<typeof flowDefinitionShapeSchema>;

/**
 * Walks the graph depth-first looking for a back edge, which is what a cycle is.
 *
 * `visiting` holds the nodes on the current path and `visited` those already cleared, so a diamond
 * (two branches rejoining) is not mistaken for a cycle the way a single "seen" set would.
 */
function hasCycle(nodeIds: string[], edges: FlowEdge[]): boolean {
  const outgoing = new Map<string, string[]>();

  for (const edge of edges) {
    const existing = outgoing.get(edge.source);

    if (existing) {
      existing.push(edge.target);
    } else {
      outgoing.set(edge.source, [edge.target]);
    }
  }

  const visiting = new Set<string>();
  const visited = new Set<string>();

  function descend(nodeId: string): boolean {
    if (visiting.has(nodeId)) {
      return true;
    }

    if (visited.has(nodeId)) {
      return false;
    }

    visiting.add(nodeId);

    for (const target of outgoing.get(nodeId) ?? []) {
      if (descend(target)) {
        return true;
      }
    }

    visiting.delete(nodeId);
    visited.add(nodeId);

    return false;
  }

  return nodeIds.some((nodeId) => descend(nodeId));
}

function checkGraph(definition: FlowDefinitionShape, ctx: z.RefinementCtx): void {
  const nodeIds = [definition.trigger.id, ...definition.steps.map((step) => step.id)];
  const knownNodeIds = new Set(nodeIds);

  if (knownNodeIds.size !== nodeIds.length) {
    ctx.addIssue({
      code: "custom",
      path: ["steps"],
      message: "Two nodes share the same id",
    });
  }

  const seenConnections = new Set<string>();

  definition.edges.forEach((edge, index) => {
    const addEdgeIssue = (message: string) => {
      ctx.addIssue({ code: "custom", path: ["edges", index], message });
    };

    if (!knownNodeIds.has(edge.source)) {
      addEdgeIssue("Edge starts at a node that does not exist");
    }

    if (!knownNodeIds.has(edge.target)) {
      addEdgeIssue("Edge ends at a node that does not exist");
    }

    if (edge.source === edge.target) {
      addEdgeIssue("A step cannot connect to itself");
    }

    // The trigger is what starts a flow, so nothing may run before it.
    if (edge.target === definition.trigger.id) {
      addEdgeIssue("Nothing can connect into the trigger");
    }

    const connection = `${edge.source}->${edge.target}`;

    if (seenConnections.has(connection)) {
      addEdgeIssue("The same two nodes are already connected");
    }

    seenConnections.add(connection);
  });

  if (hasCycle(nodeIds, definition.edges)) {
    ctx.addIssue({
      code: "custom",
      path: ["edges"],
      message: "The steps form a loop, so the flow would never finish",
    });
  }
}

export const flowDefinitionSchema = flowDefinitionShapeSchema.superRefine(checkGraph);

export type FlowDefinition = z.infer<typeof flowDefinitionSchema>;

/**
 * A brand-new flow: the trigger alone, with no steps.
 *
 * Shared rather than built in the API, so a flow created through the API and one drafted in the
 * browser start from the same document.
 */
/**
 * The address a webhook trigger listens on.
 *
 * Built from the flow's own id, so two flows can use the same path without colliding and nobody
 * has to invent a unique one. Shared rather than assembled in the UI, because the builder shows
 * this URL and the API routes on it — they must be the same string.
 */
export function buildWebhookPath(flowId: string, path: string): string {
  const suffix = path.length > 0 ? `/${path}` : "";

  return `${config.http.routes.hooks}/${flowId}${suffix}`;
}

export function createDefaultFlowDefinition(): FlowDefinition {
  return {
    version: flowConfig.definitionVersion,
    trigger: {
      id: crypto.randomUUID(),
      name: "When triggered manually",
      position: { ...flowConfig.canvas.triggerPosition },
      config: { kind: flowConfig.defaultTriggerKind },
    },
    steps: [],
    edges: [],
  };
}
